<a href="https://colab.research.google.com/github/kaiquedm12/InteligenciaArtificial/blob/main/AlgoritmosGeneticos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import random as rd
from random import randint
import matplotlib.pyplot as plt

In [ ]:
## Número de itens - 10
n=10
numero_itens=np.arange(1,n+1)

#Gerando randomicamente os pesos
pesos=[2.5,1.8,0.7,2.1,1.5,2.2,0.9,1.6,0.5,1.1]

#Gerando randomicamente os valores de cada item.
valores=[2000,1450,3400,1900,1300,1000,600,1300,400,900]

nomes=['Smartphone Samsung Galaxy S21',
'Notebook Dell Inspiron 15',
'Fone de Ouvido Bluetooth JBL',
'Smartwatch Samsung Galaxy Watch 3',
'Tablet Apple iPad 10.2',
'Câmera Digital Canon EOS Rebel T7',
'Mouse Gamer Logitech G Pro',
'Teclado Mecânico Redragon Kumara',
'Caixa de Som Bluetooth JBL GO',
'Smartband Xiaomi Mi Band 6']

# definindo o peso máximo para mochila.
max_peso_mochila=7


In [ ]:
for i in range (numero_itens.shape[0]):
  print('Item: {} \nPeso(Kg): \nValor($): {} \n'.format(nomes[i], pesos[i], valores[i]))


Item: Smartphone Samsung Galaxy S21 
Peso(Kg): 
Valor($): 2.5 

Item: Notebook Dell Inspiron 15 
Peso(Kg): 
Valor($): 1.8 

Item: Fone de Ouvido Bluetooth JBL 
Peso(Kg): 
Valor($): 0.7 

Item: Smartwatch Samsung Galaxy Watch 3 
Peso(Kg): 
Valor($): 2.1 

Item: Tablet Apple iPad 10.2 
Peso(Kg): 
Valor($): 1.5 

Item: Câmera Digital Canon EOS Rebel T7 
Peso(Kg): 
Valor($): 2.2 

Item: Mouse Gamer Logitech G Pro 
Peso(Kg): 
Valor($): 0.9 

Item: Teclado Mecânico Redragon Kumara 
Peso(Kg): 
Valor($): 1.6 

Item: Caixa de Som Bluetooth JBL GO 
Peso(Kg): 
Valor($): 0.5 

Item: Smartband Xiaomi Mi Band 6 
Peso(Kg): 
Valor($): 1.1 



In [ ]:
#Número de soluções ou indivíduos por população
solucao_por_populacao = 8
tamanho_populacao = (solucao_por_populacao,numero_itens.shape[0])

print('Tamanho da população = {}'.format(tamanho_populacao))
print('Numero de indivíduos (soluçao) = {}'.format(tamanho_populacao[0]))
print('Número itens (genes) = {}'.format(tamanho_populacao[1]))

Tamanho da população = (8, 10)
Numero de indivíduos (soluçao) = 8
Número itens (genes) = 10


In [ ]:
n_geracoes = 10

populacao_inicial = np.eye(tamanho_populacao[0],tamanho_populacao[1], k=0)

populacao_inicial = populacao_inicial.astype(int)

print('População Inicial:\n {}'.format(populacao_inicial))

População Inicial:
 [[1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]]


In [ ]:
def cal_fitness(peso, valor, populacao, max_peso_mochila):
    fitness = np.zeros(populacao.shape[0])

    for i in range(populacao.shape[0]):

      s1 = np.sum(populacao[i] * valor)
      s2 = np.sum(populacao[i] * peso)

      if s2 <= max_peso_mochila:
        fitness[i] = s1
      else:
        fitness[i] = 0

    return fitness.astype(float)

In [ ]:
cal_fitness(pesos, valores, populacao_inicial, max_peso_mochila)

array([2000., 1450., 3400., 1900., 1300., 1000.,  600., 1300.])

In [ ]:
def selecao_roleta(fitness, numero_pais, populacao):
  max_fitness = sum(fitness)

  probabilidades = fitness/max_fitness

  selecionados = populacao[np.random.choice(len(populacao), size=numero_pais, p=probabilidades)]

  return selecionados

In [ ]:
def crossover(pais, numero_filhos):
  filhos = np.zeros((numero_filhos, pais.shape[1]))

  ponto_crossover = int(pais.shape[1]/2)

  for k in range(numero_filhos):
    pai_1_idx = k%pais.shape[0]
    pai_2_idx = (k+1)%pais.shape[0]

    filhos[k, 0:ponto_crossover] = pais[pai_1_idx, 0:ponto_crossover]
    filhos[k, ponto_crossover:] = pais[pai_2_idx, ponto_crossover:]

  return filhos